name: 💅 Lint Test

on:
    push:
        branches:
            - "main"
        paths:
            - '**.go'
            - '**.mod'
    pull_request:
        branches:
          - "main"
        paths:
            - '**.go'
            - '**.mod'
    workflow_dispatch:

permissions:
    contents: read

jobs:
    lint:
        name: Lint Test
        runs-on: ubuntu-latest
        steps:
            -
                name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version:  '>=1.20'
            -
                name: Checkout code
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -
                name: Run golangci-lint
                uses: golangci/golangci-lint-action@v3
                with:
                    version: v1.52.2
