name: 🎉 release

on:
    create:
        branches:
            - main
        tags:
            - v*.*.*

jobs:
    release:
        name: Release
        runs-on: ubuntu-latest
        steps:
            -
                name: Set up Go
                uses: actions/setup-go@v5
                with:
                    go-version:  '>=1.20'
            -
                name: Checkout code
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -
                name: Run GoReleaser
                uses: goreleaser/goreleaser-action@v5
                with:
                    args: "release --clean"
                    version: latest
                env:
                    GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
                    SLACK_WEBHOOK: "${{ secrets.SLACK_WEBHOOK }}"
                    DISCORD_WEBHOOK_ID: "${{ secrets.DISCORD_WEBHOOK_ID }}"
                    DISCORD_WEBHOOK_TOKEN: "${{ secrets.DISCORD_WEBHOOK_TOKEN }}"
